### ISSUE TITLE
[Suggestion] Add /spectate for mods

### ISSUE THREAD

**Issue by Zunwolf1896** [John-Paul-R/Essential-Commands#101]
Would it be possible to add a command where certain players can have permission to go into spectator and then back into survival?

I would love for my mods to be able to /spectate players and then return to survival again, I can not currently find a way to allow them to do this without also giving them access to creative, which I am not willing to give.

**Comment by John-Paul-R** [comment]
Hmm. I don't think this quite fits in Essential Commands, but I certainly see why you'd want to do this. Is a good idea for a small mod. Or maybe this could be PRed into [Minecraft Command Permissions Fabric](https://github.com/lucko/minecraft-command-permissions-fabric).

Leaving this open for now because I might revisit it, though likely not in EC.

---

Tangentially related #104 

There is definitely interest in something like this.

**Comment by John-Paul-R** [comment]
[Vanilla Permissions](https://github.com/DrexHD/VanillaPermissions) ([Modrinth](https://modrinth.com/mod/vanilla-permissions)) should enable the desired functionality here.
