### ISSUE TITLE
Rules newline output bugged (CR characters rendered as visible in MC)

### ISSUE THREAD

**Issue by ItsaGlitch1** [John-Paul-R/Essential-Commands#181]
When displaying the rules.txt file, all lines with another line under it has a bugged character.

To reproduce:
1. press the enter key on keyboard to go to a new line
2. save the config, reload it in game
3. run /rules

![rules](https://user-images.githubusercontent.com/23035675/221429679-cffd4de8-48eb-49d1-82a7-b311634938a4.png)

Update: When starting the server or running /rules reload, the console outputs "Failed to Parse String as MinecraftText, trying Fabric Placeholder API...

**Comment by John-Paul-R** [comment]
oh, huh. I really would've thought MC would handle this automatically.

I'll fix this in an upcoming release.

Until then, there is a way to resolve this on your end. You want to save the file you're editing with "LF" line endings instead of "CRLF"

This app claims to convert one to the other automagically, could be worth a shot: https://app.execeratics.com/LFandCRLFonline/?l=en (you want CRLF to LF)

**Comment by John-Paul-R** [comment]
Resolved by #206

**Comment by altdyss** [comment]
I'm now having this issue on my server. Used notepad++ to make sure all linefeeds are LF, not carriage returns, but no dice.

**Comment by John-Paul-R** [comment]
@altdyss Interesting, could you try to upload the offending rules file here?
