### ISSUE TITLE
Permission essentialcommands.warp.tp_named.<warp_name> is not accessible or non functional

### ISSUE THREAD

**Issue by Tikkirej** [John-Paul-R/Essential-Commands#257]
On a Server, running Minecraft 1.20.1, mods Essential Commands 0.33.2 and Luckperms 5.4.102 Fabric, this set of permissions simply doesnt show up
i would like to make a set of warps inaccessible to a group of players, what can I do?
 The permission `essentialcommands.warp.tp` does show up by itself, but even manually inputting `essentialcommands.warp.tp_named.<warp_name>` doesnt work.

**Comment by John-Paul-R** [comment]
Warps are available to everyone by default. To add a permissions-gated warp, do: `/warp set <warp-name> true`

(This is because the full "warp set" syntax is `/warp set <warp-name> <requires-permission:true|false>`)

Warps created in this way should work with the `essentialcommands.warp.tp_named.<warp_name>` permission nodes.

**Comment by Tikkirej** [comment]
Ah, thank you so much! That wasn't immediately obvious to me, so that's good to know!
