### ISSUE TITLE
Dimension syntax

### ISSUE THREAD

**Issue by zorex73** [John-Paul-R/Essential-Commands#280]
When modifying the settings of the dimensions you can RTP in I couldn't figure out the nether and end's syntax. I tried the following [nether][end]. [the_nether][the_end]. [the_nether],[the_end] etc. Thank you for the help and great mod.

**Comment by John-Paul-R** [comment]
They should be the same as the vanilla identifiers (what you'd get for autocomplete for `/execute in <dimension_id>`), so `the_nether` and `the_end` _should_ be correct. (Since that hasn't worked for you, let me know how`minecraft:the_nether`, does -- that's the full name.)

I'll also double check locally

**Comment by zorex73** [comment]
I tried that and it still didn't work. I'll just send the line. 
`rtp_enabled_worlds=[overworld][minecraft:the_nether][minecraft:the_end]`

**Comment by John-Paul-R** [comment]
try

```properties
rtp_enabled_worlds=[overworld,the_nether,the_end]
```

**Comment by zorex73** [comment]
aaaaaaahhh, thank you so much, I hope you continue making this mod it is so good have a great day.

**Comment by John-Paul-R** [comment]
happy to help! Thanks for the kind words <3
