### ISSUE TITLE
[Suggestion] Being able to use /back to return to the point of death

### ISSUE THREAD

**Issue by soldeeex** [John-Paul-R/Essential-Commands#99]
Being able to use /back to return to the point of death.
Also that the mod detects if you are in the lava or in a danger zone and teleport to a nearby safe place.

**Comment by John-Paul-R** [comment]
> Being able to use /back to return to the point of death.

Sounds like you want to set `allow_back_on_death` to `true` in `config/EssentialCommands.properties`.

[See more EC Config options here](https://github.com/John-Paul-R/Essential-Commands/wiki/Config-Documentation)

---

> Also that the mod detects if you are in the lava or in a danger zone and teleport to a nearby safe place.

This is an interesting idea, but is definitely outside the realm of what Essential Commands tries to do. Reliably finding a nearby "safe" location without inadvertently giving players an ability to get into places they otherwise wouldn't be able to reach is a non-trivial task.

I do appreciate the suggestion, though.

**Comment by RockZe** [comment]
> Sounds like you want to set `allow_back_on_death` to `true` in `config/EssentialCommands.properties`.

I set the value to true, but it still didn't solve the situation! I don't know what's the matter, for the second day I can't solve the problem

**Comment by John-Paul-R** [comment]
Oh, that's... odd. And I have recently received a report of a similar issue on discord.

(will link that here in a moment)

For that person, however, the issue went away (seemingly randomly) after fiddling with their mods for a bit, so we're still unsure of the cause.

I'll repoen this issue to track the apparent bug of "it just sometimes doesn't work?!"

**Comment by John-Paul-R** [comment]
Ah, future discussion here will probably spam the original author. Will move to new issue instead lol. sorry for the confusion.

https://github.com/John-Paul-R/Essential-Commands/issues/211
